### ISSUE TITLE
Upgrade last compilation (2022-10-02) on flathub

### ISSUE THREAD

**Issue by HamHamFonFon** [flathub/org.kde.kstars#8]
Hello,
I've installed on Ubuntu with flathub the version 3.6.1 compiled on date 2022-09-29T10:17:38Z. This release don't have Ekos

After compare with a version installed on Fedora with https://snapcraft.io/install/kstars/fedora, the version installed  is version 3.6.1 with date 2022-10-02T09:29:45

Is it possible to upgrade the release on flathub ?
Thank you very much.

**Comment by travier** [comment]
What's Ekos?

**Comment by travier** [comment]
Apparently it's https://docs.kde.org/trunk5/en/kstars/kstars/tool-ekos.html. Maybe we're missing a dependency?

**Comment by travier** [comment]
See https://github.com/flathub/flathub/pull/1831#issuecomment-694385320 & https://github.com/flathub/org.kde.kstars/issues/3.

It's not possible right now to support Ekos & INDI in the KStars Flatpak.

**Comment by HamHamFonFon** [comment]
Thank you for the feed back. It's a shame that this is not possible, it is precisely one of the main interests.
I hope this will be fixed one day :).

**Comment by travier** [comment]
You can track https://github.com/flathub/org.kde.kstars/issues/3 for progress.
